### ISSUE TITLE
#INC-5312: Missing image

### ISSUE THREAD

**Issue by vanessa-cooper** [ObelusFamily/Anythink-Market-032cz#3]
Cool! Now, It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data.
Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

**Comment by stanzinofree** [comment]
Fixed bug with fallback local
![Schermata 2022-07-19 alle 11 45 07](https://user-images.githubusercontent.com/6223551/179727309-b405b454-4bad-4e25-ae10-7aa4f75e08e3.png)
![Schermata 2022-07-19 alle 11 50 21](https://user-images.githubusercontent.com/6223551/179727312-86e33255-8acf-4e84-b289-ff3c45d2edba.png)
 image when src is not available
